name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dio: ^5.7.0
  http_client_plugin:
    path: ../
  data_class_plugin: ^1.5.1

dev_dependencies:
  lints: ^5.0.0
  tachyon: ^0.3.1
  test: ^1.25.8
